"""Initial migration

Revision ID: 89c485b13ed9
Revises: 
Create Date: 2025-06-30 19:56:59.362487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89c485b13ed9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_documents_created_at'), table_name='documents')
    op.drop_index(op.f('idx_documents_filetype'), table_name='documents')
    op.drop_index(op.f('idx_documents_status'), table_name='documents')
    op.drop_index(op.f('idx_video_frames_document_id'), table_name='video_frames')
    op.drop_index(op.f('idx_video_frames_frame_index'), table_name='video_frames')
    op.drop_index(op.f('idx_video_frames_frame_number'), table_name='video_frames')
    op.drop_column('video_frames', 'frame_index')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_frames', sa.Column('frame_index', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_video_frames_frame_number'), 'video_frames', ['frame_number'], unique=False)
    op.create_index(op.f('idx_video_frames_frame_index'), 'video_frames', ['frame_index'], unique=False)
    op.create_index(op.f('idx_video_frames_document_id'), 'video_frames', ['document_id'], unique=False)
    op.create_index(op.f('idx_documents_status'), 'documents', ['status'], unique=False)
    op.create_index(op.f('idx_documents_filetype'), 'documents', ['filetype'], unique=False)
    op.create_index(op.f('idx_documents_created_at'), 'documents', ['created_at'], unique=False)
    # ### end Alembic commands ###
